### ISSUE TITLE
Fatal error: Uncaught TypeError:

### ISSUE THREAD

**Issue by bigmike7801** [kenjdavidson/oauth-yahoofantasysports#1]
I have configured the config.php file as instructed. However I'm getting the error of: `Fatal error: Uncaught TypeError: Argument 1 passed to League\OAuth2\Client\Token\AccessToken::__construct() must be of the type array, null given, called in /sites/dev.example.com/files/yahoo/oauth-yahoofantasysports/examples/index.php on line 35 and defined in /sites/dev.example.com/files/yahoo/oauth-yahoofantasysports/vendor/league/oauth2-client/src/Token/AccessToken.php:60 Stack trace: #0 /sites/dev.example.com/files/yahoo/oauth-yahoofantasysports/examples/index.php(35): League\OAuth2\Client\Token\AccessToken->__construct(NULL) #1 {main} thrown in /sites/dev.example.com/files/yahoo/oauth-yahoofantasysports/vendor/league/oauth2-client/src/Token/AccessToken.php on line 60`

Here's what my config file looks like:

```
$consumer = array(
    'clientId'      => 'my-client-id-here',
    'clientSecret'  => 'my-client-secret-here',
    'redirectUri'   => 'oob'
);

// The token should be a JSON Stringified AccessToken object
return array(
    'consumer'  => $consumer,
    'token' => ''
);
```                    

My question is, do I need to put something in the "token" field or is my config ok as shown? If I need to key in the token, where would I find this?

And yes, I've inserted my correct clientId and clientSecret.

**Comment by kenjdavidson** [comment]
Hey sorry, the documentation is not correct (or at least not complete.  If you have 'token' => then yes, it must be set to a valid value.  If you do not/have not gotten your refresh token, then you need to clear that out and go through the authentication process.

1) Clear token so that it's undefined
2) Populate everything else as you should
3) This will allow you to follow the authentication by providing you with a URL and a response code.
4) If you wish to save the auth token, THEN you would add that to your config.  From that point on your account will be refreshed.

I'll update the file now so that it makes more sense.

**Comment by kenjdavidson** [comment]
Or you could change line 33 to check the length

 if (isset($config['token']) && strlen($config['token']) > 0) { 

so that you can leave the blank token string.

**Comment by bigmike7801** [comment]
So after I removed the token parameter from the return array, I was able to get the page to populate with the "Continue to login" link: [https://api.login.yahoo.com/oauth2/request_auth?state=11b5ebe715a8dcda075d8d941fb11502&scope=fspt-w&response_type=code&approval_prompt=auto&redirect_uri=oob&client_id=dj0yJmk9QTFwOWZkVE02ZkIwJnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PTQ3](url)

However, when I click on the link, it just sends me to an error page on Yahoo that says 

> Uh oh
Looks like something went wrong.
Please try again later.

![image](https://user-images.githubusercontent.com/782338/50453207-e6935080-08f3-11e9-986b-edb23dd54b1b.png)


I'm using `oob` for the redirectUri but I've also tried using the actual uri that page is hosted as well as a couple of other things with no luck. Any chance that the link is not correct?

**Comment by kenjdavidson** [comment]
No that's the right link. That is a Yahoo error you're connecting to the right url but something in the Yahoo flow is failing.  

In your Yahoo developer console do you have a call back domain? You need a valid domain in there even if using oob in the client. If you use a call back url in the client then it has to match exactly the entry in the Yahoo developer app config.

**Comment by kenjdavidson** [comment]
I believe that the domain is not editable. So you'll need to create a new app with new codes to try it.

**Comment by bigmike7801** [comment]
I actually figured it out.

The scope was set to `scope=fspt-w` and in my app I had only asked for read access so I changed the scope to `scope=fspt-r` per the documentation here: [https://developer.yahoo.com/oauth2/guide/yahoo_scopes/#scope-identifiers=](url)

**Comment by kenjdavidson** [comment]
Boom! Awesome. Have a good one.
